baseURL: 'http://sarahrblyth.com/'
languageCode: 'en-us'
theme: 'PaperMod'
title: 'Home'

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5

params:
    custom_css: ["css/custom.css"]

    hideFooter: true
    
    profileMode:
        enabled: true
        imageUrl: "/images/profile-1500.png"
        imageTitle: "Sarah Blyth"
        imageWidth: 300
        imageHeight: 300
        title: "Sarah Blyth"
        subtitle: >
            Hi! I am the parent to a 7 year old with a rare genetic disorder and multiple disabilities. 
            I left my career as a Licensed Clinical Social Worker in the mental health field 
            to become my child’s primary caregiver. After 7 years away from the professional world, I was selected
            for the 2022-2023 [ACT LEND](https://disabilitystudies.utexas.edu/act-lend) cohort and jumped 
            at the opportunity to merge my personal and professional experiences. Upon completion of the ACT LEND 
            program, I hope to work as a family advocate in a healthcare setting. 
   
            
        # buttons:
        # - name: Blog
        # url: "/blog"

    socialIcons:
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/sarah-blyth-lcsw-42056128/"
