baseURL: 'http://sarahrblyth.com/'
languageCode: 'en-us'
theme: 'PaperMod'

params:
    hideFooter: true
    homeInfoParams:
        Title: "Sarah Blyth"
        Content: >
            I am the parent to a 7 year old with a rare genetic disorder and multiple neurodevelopmental diagnoses. 
            I am a Licensed Clinical Social Worker with experience in the mental health field, 
            but left my position to become my son’s primary caregiver. Through the [LEND](https://disabilitystudies.utexas.edu/act-lend
            ) program, I hope to merge my professional and personal experiences and find a role that allows me 
            to connect with families who have a loved one with a neurodevelopmental diagnosis. 