baseURL: 'http://sarahrblyth.com/'
languageCode: 'en-us'
theme: 'PaperMod'
title: 'Home'

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5

params:
    hideFooter: true
    
    profileMode:
        enabled: true
        imageUrl: "/images/profile-1500.png"
        imageTitle: "Sarah Blyth"
        imageWidth: 300
        imageHeight: 300
        title: "Sarah Blyth"
        subtitle: >
            I am the parent to a 7 year old with a rare genetic disorder and multiple neurodevelopmental diagnoses. 
            I left my career as a Licensed Clinical Social Worker in the mental health field to become my son’s 
            primary caregiver. After completing the [ACT LEND](https://disabilitystudies.utexas.edu/act-lend) program 
            I hope to become a family advocate that merges my personal and professional experiences.
        # buttons:
        # - name: Blog
        # url: "/blog"

    socialIcons:
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/sarah-blyth-lcsw-42056128/"
